class LoginConstants:
    """Stores  constants related to log in form"""

    LOGIN_EMAIL_FIELD_XPATH = ''
    LOGIN_PASSWORD_FIELD_XPATH = ''
    LOGIN_BUTTON_XPATH = ''

    SAVE_DATA_FOR_LOGIN_CHECKBOX = ''

    SIGN_UP_BUTTON_IN_LOGIN_XPATH = ''

    USERNAME_IN_THE_HEADER_XPATH = ''
    USERNAME_IN_THE_HEADER_TEXT = ''

    FORGET_PASSWORD_BUTTON = ''
    RESET_PASSWORD_HEADER_XPATH = ''
    RESET_PASSWORD_HEADER_TEXT = ''

    EMAIL_ERROR_MESSAGE_XPATH = ''
    PSW_ERROR_MESSAGE_XPATH = ''
    EMAIL_ERROR_MESSAGE_TEXT = ''
    PSW_ERROR_MESSAGE_TEXT = ''
